default:
  root: "C:/"
  debug: true
  server: "localhost:8000"
  source: "Source Data"
  master: "Master_Data"
  
production:
  debug: !expr Sys.getenv("ENABLE_DEBUG") == "1"
  server: !expr config::get("server", file = "/etc/server-config.yml")


  
